version: '3.8'

services:
  # PHP-FPM Container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html  # For local dev, mount your project folder
    networks:
      - laravel
    environment:
      # You can set environment variables here or rely on .env
      # APP_ENV: local
      # APP_DEBUG: 1
      # DB_HOST: db
      # DB_DATABASE: laravel
      # DB_USERNAME: laravel
      # DB_PASSWORD: laravel
    depends_on:
      - db

  # Nginx Container
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # MariaDB Container
  db:
    image: mariadb:10.8
    container_name: laravel_db
    environment:
      # Uses the same environment variables as MySQL images
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
